# Generated by Django 6.0.1 on 2026-01-27 14:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/')),
                ('raw_text', models.TextField(blank=True)),
                ('predicted_action', models.CharField(blank=True, max_length=100)),
                ('predicted_data', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('sunlight_level', models.CharField(choices=[('FULL_SUN', 'Full Sun'), ('PARTIAL', 'Partial'), ('SHADE', 'Shade')], default='FULL_SUN', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('SEEDLING', 'Seedling'), ('VEGETATIVE', 'Vegetative'), ('FLOWERING', 'Flowering'), ('HARVESTED', 'Harvested'), ('DEAD', 'Dead')], default='SEEDLING', max_length=20)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='core.zone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GardenEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('WATER', 'Water'), ('PLANT', 'Plant'), ('SEED', 'Seed'), ('NOTE', 'Note'), ('HARVEST', 'Harvest'), ('FERTILIZE', 'Fertilize')], max_length=20)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.plant')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.zone')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
