# Generated by Django 6.0.1 on 2026-01-28 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='gardenevent',
            name='parent_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_events', to='core.gardenevent'),
        ),
        migrations.AddField(
            model_name='zone',
            name='irrigation_type',
            field=models.CharField(blank=True, choices=[('DRIP', 'Drip'), ('MANUAL', 'Manual'), ('SPRINKLER', 'Sprinkler'), ('NONE', 'None')], default='NONE', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='size_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='sun_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='gardenevent',
            name='event_type',
            field=models.CharField(choices=[('WATER', 'Water'), ('PLANT', 'Plant'), ('SOW', 'Sow'), ('GERMINATE', 'Germinate'), ('TRANSPLANT', 'Transplant'), ('FIRST_HARVEST', 'First Harvest'), ('TERMINATE', 'Terminate'), ('NOTE', 'Note'), ('HARVEST', 'Harvest'), ('FERTILIZE', 'Fertilize'), ('HEALTH_CHECK', 'Health Check')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='status',
            field=models.CharField(choices=[('SEEDLING', 'Seedling'), ('GERMINATED', 'Germinated'), ('PLANTED', 'Planted'), ('PROVIDING', 'Providing'), ('REMOVED', 'Removed')], default='SEEDLING', max_length=20),
        ),
    ]
