# Generated by Django 6.0.1 on 2026-01-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_species_plant_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestqueue',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='ingest/audio/'),
        ),
        migrations.AddField(
            model_name='ingestqueue',
            name='transcript_clean',
            field=models.TextField(blank=True, help_text='AI cleaned version (no fluff)'),
        ),
    ]
